spring:
    application:
        name: demo
    datasource:
        url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: test
        password: test
        #    driver-class-name: oracle.jdbc.OracleDriver
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: ${DB_MAX_POOL_SIZE:3} # keep it as small as possible for better performance.
            data-source-properties:
                ApplicationName: ${spring.application.name} # show application's name when using pg_stat_activity
                stringtype: unspecified
                reWriteBatchedInserts: true

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create
        #    show-sql: true
        properties:
            hibernate:
                jdbc.batch_size: 50
                order_inserts: true
                order_updates: true
        #        "[format_sql]": true
        #    database-platform: org.hibernate.dialect.OracleDialect
        database-platform: org.hibernate.dialect.MySQLDialect


server:
  error:
    whitelabel:
      enabled: false # disable default whitelabel error page.
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    show-details: always
